### ISSUE TITLE
unable to stand up web service on raspberry pi

### ISSUE THREAD

**Issue by breadlam** [wger-project/docker#11]
I've followed the instructions for "1 - Start":
```
docker-compose up -d
docker-compose exec web python3 manage.py sync-exercises
docker-compose exec web python3 manage.py download-exercise-images
docker-compose exec web wger load-online-fixtures
```

However, no web service was found.
![image](https://user-images.githubusercontent.com/74521596/133830447-bb8b77a8-46ab-4907-98aa-f26576e2f36d.png)

Log Output:
```
pi@wgerpi:~/projects/wger-docker $ sudo docker-compose up -d
Creating network "wger-docker_default" with the default driver
Creating wger-docker_cache_1 ... done
Creating wger-docker_db_1    ... done
Creating wger-docker_web_1   ... done
Creating wger-docker_nginx_1 ... done
pi@wgerpi:~/projects/wger-docker $ sudo docker-compose logs -f
Attaching to wger-docker_nginx_1, wger-docker_web_1, wger-docker_cache_1, wger-docker_db_1
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2021-09-17 17:14:43.246 UTC [1] LOG:  starting PostgreSQL 12.8 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
db_1     | 2021-09-17 17:14:43.246 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2021-09-17 17:14:43.246 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2021-09-17 17:14:44.556 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2021-09-17 17:14:44.648 UTC [22] LOG:  database system was shut down at 2021-09-17 17:01:45 UTC
db_1     | 2021-09-17 17:14:44.721 UTC [1] LOG:  database system is ready to accept connections
cache_1  | 1:C 17 Sep 2021 17:14:37.545 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache_1  | 1:C 17 Sep 2021 17:14:37.545 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
cache_1  | 1:C 17 Sep 2021 17:14:37.545 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cache_1  | 1:M 17 Sep 2021 17:14:37.547 * monotonic clock: POSIX clock_gettime
cache_1  | 1:M 17 Sep 2021 17:14:37.570 * Running mode=standalone, port=6379.
cache_1  | 1:M 17 Sep 2021 17:14:37.571 # Server initialized
cache_1  | 1:M 17 Sep 2021 17:14:37.571 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cache_1  | 1:M 17 Sep 2021 17:14:37.575 * Ready to accept connections
nginx_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1  | 2021/09/17 17:15:31 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/nginx.conf:2
nginx_1  | nginx: [emerg] host not found in upstream "web" in /etc/nginx/conf.d/nginx.conf:2
web_1    | standard_init_linux.go:228: exec user process caused: exec format error
wger-docker_nginx_1 exited with code 1
wger-docker_web_1 exited with code 1
```

It looks like the issue is probably here:
`web_1    | standard_init_linux.go:228: exec user process caused: exec format error`

Are there any known issues with using your `wger/devel:latest` image on a raspberry pi (aarch64)?

**Comment by breadlam** [comment]
This confirms my suspicion:
```
pi@wgerpi:~/projects/wger-docker $ sudo docker run -it wger/devel:latest bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by rolandgeider** [comment]
Thanks for reporting this. Do you mean that you started the images on a Pi?

You are also not the first one to ask about (native) ARM support. The only reason there are no arm images is lack of time

**Comment by breadlam** [comment]
Thanks! I'll work on building an image for arm64.

**Comment by rolandgeider** [comment]
That would be awesome! In theory you shouldn't need to do more than installing the correct packages and dependencies. If I can be of any help, just ping me

**Comment by breadlam** [comment]
I was able to get wger running on a raspberry pi, by building `wger/base`, `wger/devel`, and `wger/apache` locally before invoking `docker-compose`:
```
git clone https://github.com/wger-project/wger
git clone https://github.com/wger-project/docker wger-docker
cd wger
docker build -f extras/docker/base/Dockerfile -t wger/base:2.1-dev .
docker build -f extras/docker/development/Dockerfile -t wger/devel .
docker build -f extras/docker/apache/Dockerfile --tag wger/apache .
cd ../wger-docker
docker-compose up -d
```

However, I'm running into an issue when running `docker-compose exec web python3 manage.py sync-exercises`
```
*** Synchronizing categories...
done!

*** Synchronizing muscles...
done!

*** Synchronizing equipment...
done!

*** Synchronizing exercises...
Traceback (most recent call last):
  File "/home/wger/src/manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/wger/src/wger/exercises/management/commands/sync-exercises.py", line 172, in handle
    exercise.exercise_base.category_id = data['category']['id']
AttributeError: 'NoneType' object has no attribute 'category_id'
```

I'm guessing it's probably a version issue, caused by cloning the latest wger changes and building `wger/base`, but I'm not sure.

**Comment by breadlam** [comment]
Would it be possible to have Github generate arm64 docker images automatically?

Reading around a little, it looks like a change to the github workflow config to do that might look something like this:
```
diff --git a/.github/workflows/docker-base.yml b/.github/workflows/docker-base.yml
index 4cc4c644..8f2bc371 100644
--- a/.github/workflows/docker-base.yml
+++ b/.github/workflows/docker-base.yml
@@ -26,6 +26,7 @@ jobs:
       - name: Build base image
         uses: docker/build-push-action@v2.7.0
         with:
+          platforms: linux/amd64,linux/arm64/v8
           context: .
           file: extras/docker/base/Dockerfile
           push: true
diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
index 12c24e42..f097d14d 100644
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -27,6 +27,7 @@ jobs:
       - name: Build apache image
         uses: docker/build-push-action@v2.7.0
         with:
+          platforms: linux/amd64,linux/arm64/v8
           context: .
           file: extras/docker/apache/Dockerfile
           push: true
@@ -35,6 +36,7 @@ jobs:
       - name: Build dev image
         uses: docker/build-push-action@v2.7.0
         with:
+          platforms: linux/amd64,linux/arm64/v8
           context: .
           file: extras/docker/development/Dockerfile
           push: true
```

However, I haven't tested it.

**Comment by rolandgeider** [comment]
Did you need to change anything in the docker files themselves before building the images? If changing the platforms is the only thing need this would be great. I'll test this when I find some free time

**Comment by breadlam** [comment]
> Did you need to change anything in the docker files themselves before building the images?

Nope! Once I figured out how the docker images depended on each other, I was able to just run those commands. The other docker images that are pulled down already have arm64 versions available, so things just worked.

I did change some of docker's timeout settings, because the raspberry pi is so slow, but that was independent of wger:
```
export COMPOSE_HTTP_TIMEOUT=300
export DOCKER_CLIENT_TIMEOUT=300
```

**Comment by rolandgeider** [comment]
I just updated the workflow files with the platforms. Could you check that the regular images work on your pi?

**Comment by breadlam** [comment]
We already interacted on discord, but I'm recording the results here for posterity, in case someone else running wger on a raspberry pi 4 stumbles across this ticket.

(TL;DR Everything worked, with no modifications on my part.)

On a fresh installation of Debian `buster`, with docker installed [using Docker's instructions](https://docs.docker.com/engine/install/debian/), and `docker-compose` installed via `pip3`, I was able to clone the wger docker repo and successfully download, build, and start wger's various containers:
![image](https://user-images.githubusercontent.com/74521596/134982209-8e73e29f-938c-437c-9993-22f9080e5cdd.png)

Once the containers were running, all services were launched successfully:
```
pi@raspberrypi:~/wger-docker $ docker-compose logs -f
Attaching to wger-docker_nginx_1, wger-docker_web_1, wger-docker_cache_1, wger-docker_db_1
cache_1  | 1:C 27 Sep 2021 19:50:28.397 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache_1  | 1:C 27 Sep 2021 19:50:28.397 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
cache_1  | 1:C 27 Sep 2021 19:50:28.397 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cache_1  | 1:M 27 Sep 2021 19:50:28.400 * monotonic clock: POSIX clock_gettime
cache_1  | 1:M 27 Sep 2021 19:50:28.401 * Running mode=standalone, port=6379.
cache_1  | 1:M 27 Sep 2021 19:50:28.401 # Server initialized
cache_1  | 1:M 27 Sep 2021 19:50:28.401 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cache_1  | 1:M 27 Sep 2021 19:50:28.406 * Ready to accept connections
db_1     | The files belonging to this database system will be owned by user "postgres".
db_1     | This user must also own the server process.
db_1     | 
db_1     | The database cluster will be initialized with locale "en_US.utf8".
db_1     | The default database encoding has accordingly been set to "UTF8".
db_1     | The default text search configuration will be set to "english".
db_1     | 
db_1     | Data page checksums are disabled.
db_1     | 
db_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1     | creating subdirectories ... ok
db_1     | selecting dynamic shared memory implementation ... posix
db_1     | selecting default max_connections ... 100
db_1     | selecting default shared_buffers ... 128MB
db_1     | selecting default time zone ... UTC
db_1     | creating configuration files ... ok
db_1     | running bootstrap script ... ok
db_1     | sh: locale: not found
db_1     | 2021-09-27 19:50:30.610 UTC [30] WARNING:  no usable system locales were found
db_1     | performing post-bootstrap initialization ... ok
db_1     | syncing data to disk ... ok
db_1     | 
db_1     | 
db_1     | Success. You can now start the database server using:
db_1     | 
db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1     | initdb: warning: enabling "trust" authentication for local connections
db_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_1     | --auth-local and --auth-host, the next time you run initdb.
db_1     | 
db_1     | waiting for server to start....2021-09-27 19:50:37.034 UTC [35] LOG:  starting PostgreSQL 12.8 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
db_1     | 2021-09-27 19:50:37.056 UTC [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2021-09-27 19:50:37.164 UTC [36] LOG:  database system was shut down at 2021-09-27 19:50:32 UTC
db_1     | 2021-09-27 19:50:37.204 UTC [35] LOG:  database system is ready to accept connections
db_1     |  done
db_1     | server started
db_1     | CREATE DATABASE
db_1     | 
db_1     | 
db_1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1     | 
db_1     | waiting for server to shut down....2021-09-27 19:50:37.953 UTC [35] LOG:  received fast shutdown request
db_1     | 2021-09-27 19:50:37.959 UTC [35] LOG:  aborting any active transactions
db_1     | 2021-09-27 19:50:37.960 UTC [35] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
db_1     | 2021-09-27 19:50:37.961 UTC [37] LOG:  shutting down
db_1     | 2021-09-27 19:50:38.087 UTC [35] LOG:  database system is shut down
db_1     |  done
db_1     | server stopped
db_1     | 
db_1     | PostgreSQL init process complete; ready for start up.
db_1     | 
db_1     | 2021-09-27 19:50:38.183 UTC [1] LOG:  starting PostgreSQL 12.8 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
db_1     | 2021-09-27 19:50:38.183 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2021-09-27 19:50:38.183 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2021-09-27 19:50:38.560 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2021-09-27 19:50:38.780 UTC [49] LOG:  database system was shut down at 2021-09-27 19:50:38 UTC
db_1     | 2021-09-27 19:50:38.876 UTC [1] LOG:  database system is ready to accept connections
db_1     | 2021-09-27 19:50:40.670 UTC [57] ERROR:  relation "auth_user" does not exist at character 35
db_1     | 2021-09-27 19:50:40.670 UTC [57] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "auth_user"
nginx_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: using the "epoll" event method
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: nginx/1.20.1
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: built by gcc 8.3.0 (Debian 8.3.0-6) 
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: OS: Linux 5.10.60-v8+
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: start worker processes
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: start worker process 24
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: start worker process 25
web_1    | Waiting for postgres...
web_1    | PostgreSQL started :)
web_1    | *** Database does not exist, creating one now
web_1    | Operations to perform:
web_1    |   Apply all migrations: auth, authtoken, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight
web_1    | Running migrations:
web_1    |   Applying contenttypes.0001_initial... OK
web_1    |   Applying contenttypes.0002_remove_content_type_name... OK
web_1    |   Applying auth.0001_initial... OK
web_1    |   Applying auth.0002_alter_permission_name_max_length... OK
web_1    |   Applying auth.0003_alter_user_email_max_length... OK
web_1    |   Applying auth.0004_alter_user_username_opts... OK
web_1    |   Applying auth.0005_alter_user_last_login_null... OK
web_1    |   Applying auth.0006_require_contenttypes_0002... OK
web_1    |   Applying auth.0007_alter_validators_add_error_messages... OK
web_1    |   Applying auth.0008_alter_user_username_max_length... OK
web_1    |   Applying auth.0009_alter_user_last_name_max_length... OK
web_1    |   Applying auth.0010_alter_group_name_max_length... OK
web_1    |   Applying auth.0011_update_proxy_permissions... OK
web_1    |   Applying auth.0012_alter_user_first_name_max_length... OK
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: start worker process 26
nginx_1  | 2021/09/27 19:50:40 [notice] 1#1: start worker process 27
web_1    |   Applying authtoken.0001_initial... OK
web_1    |   Applying authtoken.0002_auto_20160226_1747... OK
web_1    |   Applying authtoken.0003_tokenproxy... OK
web_1    |   Applying gym.0001_initial... OK
web_1    |   Applying core.0001_initial... OK
web_1    |   Applying config.0001_initial... OK
web_1    |   Applying config.0002_auto_20190618_1617... OK
web_1    |   Applying gym.0002_auto_20151003_1944... OK
web_1    |   Applying gym.0003_auto_20151003_2008... OK
web_1    |   Applying gym.0004_auto_20151003_2357... OK
web_1    |   Applying gym.0005_auto_20151023_1522... OK
web_1    |   Applying gym.0006_auto_20160214_1013... OK
web_1    |   Applying gym.0007_auto_20170123_0920... OK
web_1    |   Applying gym.0008_auto_20190618_1617... OK
web_1    |   Applying exercises.0001_initial... OK
web_1    |   Applying manager.0001_initial... OK
web_1    |   Applying manager.0002_auto_20150202_2040... OK
web_1    |   Applying manager.0004_auto_20150609_1603... OK
web_1    |   Applying core.0002_auto_20141225_1512... OK
web_1    |   Applying core.0003_auto_20150217_1554... OK
web_1    |   Applying core.0004_auto_20150217_1914... OK
web_1    |   Applying core.0005_auto_20151025_2236... OK
web_1    |   Applying core.0006_auto_20151025_2237... OK
web_1    |   Applying core.0007_repetitionunit... OK
web_1    |   Applying core.0008_weightunit... OK
web_1    |   Applying core.0009_auto_20160303_2340... OK
web_1    |   Applying core.0010_auto_20170403_0144... OK
web_1    |   Applying core.0011_auto_20201201_0653... OK
web_1    |   Applying core.0012_auto_20210210_1228... OK
web_1    |   Applying core.0013_auto_20210726_1729... OK
web_1    |   Applying easy_thumbnails.0001_initial... OK
web_1    |   Applying easy_thumbnails.0002_thumbnaildimensions... OK
web_1    |   Applying exercises.0002_auto_20150307_1841... OK
web_1    |   Applying exercises.0003_auto_20160921_2000... OK
web_1    |   Applying exercises.0004_auto_20170404_0114... OK
web_1    |   Applying exercises.0005_auto_20190618_1617... OK
web_1    |   Applying exercises.0006_auto_20201203_0203... OK
web_1    |   Applying exercises.0007_auto_20201203_1042... OK
web_1    |   Applying exercises.0008_exercisebase... OK
web_1    |   Applying exercises.0009_auto_20201211_0139... OK
web_1    |   Applying exercises.0010_auto_20201211_0205... OK
web_1    |   Applying exercises.0011_auto_20201214_0033... OK
web_1    |   Applying exercises.0012_auto_20210327_1219... OK
web_1    |   Applying exercises.0013_auto_20210503_1232... OK
web_1    |   Applying exercises.0014_exerciseimage_style... OK
web_1    |   Applying gallery.0001_initial... OK
web_1    |   Applying mailer.0001_initial... OK
web_1    |   Applying mailer.0002_auto_20190618_1617... OK
web_1    |   Applying mailer.0003_auto_20201201_0653... OK
web_1    |   Applying manager.0005_auto_20160303_2008... OK
web_1    |   Applying manager.0006_auto_20160303_2138... OK
web_1    |   Applying manager.0007_auto_20160311_2258... OK
web_1    |   Applying manager.0008_auto_20190618_1617... OK
web_1    |   Applying manager.0009_auto_20201202_1559... OK
web_1    |   Applying manager.0010_auto_20210102_1446... OK
web_1    |   Applying manager.0011_remove_set_exercises... OK
web_1    |   Applying manager.0012_auto_20210430_1449... OK
web_1    |   Applying manager.0013_set_comment... OK
web_1    |   Applying manager.0014_auto_20210717_1858... OK
web_1    |   Applying measurements.0001_initial... OK
web_1    |   Applying measurements.0002_auto_20210722_1042... OK
web_1    |   Applying nutrition.0001_initial... OK
web_1    |   Applying nutrition.0002_auto_20170101_1538... OK
web_1    |   Applying nutrition.0003_auto_20170118_2308... OK
web_1    |   Applying nutrition.0004_auto_20200819_2310... OK
web_1    |   Applying nutrition.0005_logitem... OK
web_1    |   Applying nutrition.0006_auto_20201201_0653... OK
web_1    |   Applying nutrition.0007_auto_20201214_0013... OK
web_1    |   Applying nutrition.0008_auto_20210102_1446... OK
web_1    |   Applying nutrition.0009_meal_name... OK
web_1    |   Applying sessions.0001_initial... OK
web_1    |   Applying sites.0001_initial... OK
web_1    |   Applying sites.0002_alter_domain_unique... OK
web_1    |   Applying weight.0001_initial... OK
web_1    |   Applying weight.0002_auto_20150604_2139... OK
web_1    |   Applying weight.0003_auto_20160416_1030... OK
web_1    | Installed 1 object(s) from 1 fixture(s)
web_1    | Installed 16 object(s) from 1 fixture(s)
web_1    | Installed 6 object(s) from 1 fixture(s)
web_1    | Installed 3 object(s) from 1 fixture(s)
web_1    | Installed 5 object(s) from 1 fixture(s)
web_1    | Installed 7 object(s) from 1 fixture(s)
web_1    | Installed 6 object(s) from 1 fixture(s)
web_1    | Installed 6 object(s) from 1 fixture(s)
web_1    | Installed 512 object(s) from 1 fixture(s)
web_1    | Installed 1 object(s) from 1 fixture(s)
web_1    | Installed 10 object(s) from 1 fixture(s)
web_1    | Installed 16 object(s) from 1 fixture(s)
web_1    | Installed 7 object(s) from 1 fixture(s)
web_1    | Installed 355 object(s) from 1 fixture(s)
web_1    | Installed 528 object(s) from 1 fixture(s)
web_1    | Installed 1 object(s) from 1 fixture(s)
web_1    | Installed 1 object(s) from 1 fixture(s)
web_1    | Installed 1 object(s) from 1 fixture(s)
web_1    | *** Password for user admin was reset to 'adminadmin'
web_1    | Installed 3 object(s) from 1 fixture(s)
web_1    | yarn install v1.22.5
web_1    | [1/5] Validating package.json...
web_1    | [2/5] Resolving packages...
web_1    | [3/5] Fetching packages...
web_1    | [4/5] Linking dependencies...
web_1    | [5/5] Building fresh packages...
web_1    | Done in 31.97s.
web_1    | yarn run v1.22.5
web_1    | $ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
web_1    | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
web_1    | 
web_1    | Recommendation: math.div($spacer, 2)
web_1    | 
web_1    | More info and automated migrator: https://sass-lang.com/d/slash-div
web_1    | 
web_1    |     ╷
web_1    | 302 │ $headings-margin-bottom:      $spacer / 2 !default;
web_1    |     │                               ^^^^^^^^^^^
web_1    |     ╵
web_1    |     wger/core/static/yarn/bootstrap/scss/_variables.scss 302:31  @import
web_1    |     wger/core/static/scss/main.scss 46:9                         root stylesheet
web_1    | 
web_1    | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
web_1    | 
web_1    | Recommendation: math.div($input-padding-y, 2)
web_1    | 
web_1    | More info and automated migrator: https://sass-lang.com/d/slash-div
web_1    | 
web_1    |     ╷
web_1    | 498 │ $input-height-inner-quarter:            add($input-line-height * .25em, $input-padding-y / 2) !default;
web_1    |     │                                                                         ^^^^^^^^^^^^^^^^^^^^
web_1    |     ╵
web_1    |     wger/core/static/yarn/bootstrap/scss/_variables.scss 498:73  @import
web_1    |     wger/core/static/scss/main.scss 46:9                         root stylesheet
web_1    | 
web_1    | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
web_1    | 
web_1    | Recommendation: math.div($custom-control-indicator-size, 2)
web_1    | 
web_1    | More info and automated migrator: https://sass-lang.com/d/slash-div
web_1    | 
web_1    |     ╷
web_1    | 568 │ $custom-switch-indicator-border-radius:         $custom-control-indicator-size / 2 !default;
web_1    |     │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_1    |     ╵
web_1    |     wger/core/static/yarn/bootstrap/scss/_variables.scss 568:49  @import
web_1    |     wger/core/static/scss/main.scss 46:9                         root stylesheet
web_1    | 
web_1    | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
web_1    | 
web_1    | Recommendation: math.div($spacer, 2)
web_1    | 
web_1    | More info and automated migrator: https://sass-lang.com/d/slash-div
web_1    | 
web_1    |     ╷
web_1    | 713 │ $nav-divider-margin-y:              $spacer / 2 !default;
web_1    |     │                                     ^^^^^^^^^^^
web_1    |     ╵
web_1    |     wger/core/static/yarn/bootstrap/scss/_variables.scss 713:37  @import
web_1    |     wger/core/static/scss/main.scss 46:9                         root stylesheet
web_1    | 
web_1    | DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
web_1    | 
web_1    | Recommendation: math.div($spacer, 2)
web_1    | 
web_1    | More info and automated migrator: https://sass-lang.com/d/slash-div
web_1    | 
web_1    |     ╷
web_1    | 718 │ $navbar-padding-y:                  $spacer / 2 !default;
web_1    |     │                                     ^^^^^^^^^^^
web_1    |     ╵
web_1    |     wger/core/static/yarn/bootstrap/scss/_variables.scss 718:37  @import
web_1    |     wger/core/static/scss/main.scss 46:9                         root stylesheet
web_1    | 
web_1    | WARNING: 67 repetitive deprecation warnings omitted.
web_1    | Run in verbose mode to see all warnings.
web_1    | 
web_1    | Done in 8.82s.
web_1    | Running in production mode, running collectstatic now
web_1    | 
web_1    | 6021 static files copied to '/home/wger/static'.
web_1    | Using gunicorn...
web_1    | [2021-09-27 19:52:20 +0000] [60] [INFO] Starting gunicorn 20.1.0
web_1    | [2021-09-27 19:52:20 +0000] [60] [INFO] Listening at: http://0.0.0.0:8000 (60)
web_1    | [2021-09-27 19:52:20 +0000] [60] [INFO] Using worker: sync
web_1    | [2021-09-27 19:52:20 +0000] [61] [INFO] Booting worker with pid: 61
```

I was able to bring up the local wger instance in a browser:
![image](https://user-images.githubusercontent.com/74521596/134982722-0f7646ae-be29-4fd7-b229-cfff2572409c.png)

Following the [simple docker instructions](https://github.com/wger-project/docker) to update exercises, images, and fixtures, everything worked as expected: 
https://pastebin.com/raw/SJqYhhzd

And here are some benchmarks (Raspberry Pi 4, using a Samsung Evo 64GB flash card):
- 20 seconds to take down the containers
- 9 seconds to stand up the containers
- 52 seconds to finish starting container services
- 58 seconds to sync exercises
- 1m 28s to download exercise images
- 9m 40s to load online fixtures 

Cheers!
