### ISSUE TITLE
docker-compose exec web wger load-online-fixtures Leads to Command: 'invoke load-online-fixtures'  Exit code: -9

### ISSUE THREAD

**Issue by hendawyjr** [wger-project/docker#12]
docker-compose exec web wger load-online-fixtures
*** No settings given, using /home/wger/src/settings.py
Downloading fixture data from https://github.com/wger-project/data/raw/master/fixtures/ingredients.json.zip...
-> fixture size: 5.03 MB
-> saving to temp file /tmp/tmpp4vq6u0i.json.zip
Traceback (most recent call last):
  File "/usr/local/bin/wger", line 33, in <module>
    sys.exit(load_entry_point('wger', 'console_scripts', 'wger')())
  File "/home/wger/src/wger/__main__.py", line 40, in main
    run(invoke_cmd + ' '.join(args), pty=True)
  File "/usr/local/lib/python3.9/dist-packages/invoke/__init__.py", line 48, in run
    return Context().run(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/context.py", line 95, in run
    return self._run(runner, command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/context.py", line 102, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'invoke load-online-fixtures'

Exit code: -9

Stdout: already printed

Stderr: n/a (PTYs have no stderr)

**Comment by hendawyjr** [comment]
Am not an expert, so excuse me if its a simple nodge 😥✌

**Comment by rolandgeider** [comment]
You are right, that traceback gives basically no information. My only guess would be that there was a problem while writing the tmp file? Have you tried running the command again? In any case I'll try to reproduce it

**Comment by hendawyjr** [comment]
Yes, sadly using command reproduces same error.

I have stopped and removed Containers using `docker-compose down`
then pruned all non linked data including volumes with `docker prune --volumes`
and re initiated the compose again `docker-compose up -d `
nothing changed importing images works perfectly fine but 
however no change,

**Comment by rolandgeider** [comment]
I just tried this on a fresh install and it worked fine. You might want to try to download the ingredient file into the container and loading it manually

**Comment by rolandgeider** [comment]
Actually, after doing some quick googling, exit code 9 might mean that the system was running out of memory and the OS terminated the process. You might have some luck giving the docker process more RAM (I can't tell you exactly how much is needed for the application to import the fixture)

**Comment by rolandgeider** [comment]
closing here, if you still have the problem just open the issue again
