### ISSUE TITLE
Almost there... so close - Problems launching

### ISSUE THREAD

**Issue by nicolasshu** [wger-project/docker#3]
I'm almost there! I am having a few issues, and I haven't been able to figure out what to do about this. This is what I get when I try to open the port on my browser

```
Environment:


Request Method: GET
Request URL: http://192.168.1.9/en/software/features

Django Version: 3.1.5
Python Version: 3.8.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_extensions',
 'storages',
 'wger.config',
 'wger.core',
 'wger.mailer',
 'wger.exercises',
 'wger.gym',
 'wger.manager',
 'wger.nutrition',
 'wger.software',
 'wger.utils',
 'wger.weight',
 'captcha',
 'django.contrib.sitemaps',
 'easy_thumbnails',
 'compressor',
 'crispy_forms',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_bootstrap_breadcrumbs',
 'corsheaders')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'wger.utils.middleware.JavascriptAJAXRedirectionMiddleware',
 'wger.utils.middleware.WgerAuthenticationMiddleware',
 'wger.utils.middleware.RobotsExclusionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware')



Traceback (most recent call last):
  File "/home/wger/src/wger/utils/language.py", line 55, in load_language
    language = Language.objects.get(short_name=used_language)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(

During handling of the above exception (Language matching query does not exist.), another exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wger/src/wger/software/views.py", line 35, in features
    return render(request, 'features.html', context)
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/django/template/context.py", line 244, in bind_template
    updates.update(processor(self.request))
  File "/home/wger/src/wger/utils/context_processor.py", line 29, in processor
    language = load_language()
  File "/home/wger/src/wger/utils/language.py", line 58, in load_language
    language = Language.objects.get(short_name="en")
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /en/software/features
Exception Value: Language matching query does not exist.
```

Likewise, this is the error on the `*-web` container

```
Waiting for postgres...,
PostgreSQL started :),
yarn install v1.22.5
,
[1/5] Validating package.json...
,
[2/5] Resolving packages...
,
[3/5] Fetching packages...
,
[4/5] Linking dependencies...
,
warning " > bootstrap@4.5.2" has unmet peer dependency "popper.js@^1.16.1".
,
[5/5] Building fresh packages...
,
Done in 20.74s.
,
yarn run v1.22.5
,
$ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
,
Done in 7.45s.
,
Running in production mode, running collectstatic now,
,
4514 static files copied to '/home/wger/static', 279 unmodified.,
Using gunicorn...,
[2021-01-14 04:45:34 +0000] [59] [INFO] Starting gunicorn 20.0.4,
[2021-01-14 04:45:34 +0000] [59] [INFO] Listening at: http://0.0.0.0:8000 (59),
[2021-01-14 04:45:34 +0000] [59] [INFO] Using worker: sync,
[2021-01-14 04:45:35 +0000] [61] [INFO] Booting worker with pid: 61,
Internal Server Error: /en/software/features,
Traceback (most recent call last):,
  File "/home/wger/src/wger/utils/language.py", line 55, in load_language,
    language = Language.objects.get(short_name=used_language),
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method,
    return getattr(self.get_queryset(), name)(*args, **kwargs),
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get,
    raise self.model.DoesNotExist(,
wger.core.models.Language.DoesNotExist: Language matching query does not exist.,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner,
    response = get_response(request),
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response,
    response = wrapped_callback(request, *callback_args, **callback_kwargs),
  File "/home/wger/src/wger/software/views.py", line 35, in features,
    return render(request, 'features.html', context),
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render,
    content = loader.render_to_string(template_name, context, request, using=using),
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string,
    return template.render(context, request),
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 61, in render,
    return self.template.render(context),
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 168, in render,
    with context.bind_template(self):,
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__,
    return next(self.gen),
  File "/usr/local/lib/python3.8/dist-packages/django/template/context.py", line 244, in bind_template,
    updates.update(processor(self.request)),
  File "/home/wger/src/wger/utils/context_processor.py", line 29, in processor,
    language = load_language(),
  File "/home/wger/src/wger/utils/language.py", line 58, in load_language,
    language = Language.objects.get(short_name="en"),
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method,
    return getattr(self.get_queryset(), name)(*args, **kwargs),
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get,
    raise self.model.DoesNotExist(,
wger.core.models.Language.DoesNotExist: Language matching query does not exist.,
```

Do you understand what is wrong with this and how I can make it work?
Thank you very much!

**Comment by rolandgeider** [comment]
That the language can't be found means that some of the fixtures with the initial data could not be loaded. You can either delete the DB and start the container again or `exec` into web and do `wger bootstrap`

**Comment by thelfensdrfer** [comment]
I have the same problem:

```bash
$ docker-compose exec web wger bootstrap
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.15s.
yarn run v1.22.5
$ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
Done in 2.36s.
```

```bash
$ docker-compose exec web python3 manage.py migrate
Operations to perform:
  Apply all migrations: auth, authtoken, config, contenttypes, core, easy_thumbnails, exercises, gym, mailer, manager, nutrition, sessions, sites, weight
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by rolandgeider** [comment]
That there are are changes is normal, everytime you change e.g. the available options in a drop-down it would also generate a new migration, even if it won't change anything in the db. Did you also get the problem with the initial data?

**Comment by thelfensdrfer** [comment]
Yeah, just wanted to show to you that I applied all migrations.

**Comment by rolandgeider** [comment]
This should be fixed in the meantime, closing here. If it happens again, obviously reopen
