### ISSUE TITLE
Docker: Error downloading exercise-images

### ISSUE THREAD

**Issue by Lordpedal** [wger-project/docker#4]
When I try to update the exercise-images of the docker I obtain this error:

```bash
lordpedal@overclock:~/docker/wger$ docker-compose exec web python3 manage.py download-exercise-images

*** Processing 2 Handed Kettlebell Swing (ID: 345, UUID: c788d643-150a-4ac7-97ef-84643c6419bf)
    No images for this exercise, nothing to do

*** Processing Abduktoren-Maschine (ID: 174, UUID: 99881bdd-43d7-4c3b-82ed-9c187d0455b7)
    No images for this exercise, nothing to do

*** Processing Adduktoren Maschine (ID: 223, UUID: e56d0a17-b1b8-427d-991e-97c530c7db6a)
    No images for this exercise, nothing to do

*** Processing Arnold Press (ID: 228, UUID: 880bff63-6798-4ffc-a818-b2a1ccfec0f7)
    Fetching image 193 - Arnold-press-2.png
    --> Image not found in local DB, creating now...
Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/wger/src/wger/exercises/management/commands/download-exercise-images.py", line 137, in handle
    image.exercise = exercise
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/related_descriptors.py", line 215, in __set__
    raise ValueError(
ValueError: Cannot assign "<Exercise: Arnold Press>": "ExerciseImage.exercise" must be a "ExerciseBase" instance.
```
Meanwhile the other command work fine, without fails:

```bash
lordpedal@overclock:~/docker/wger$ docker-compose exec web wger load-online-fixtures
*** No settings given, using /home/wger/src/settings.py
Downloading fixture data from https://github.com/wger-project/data/raw/master/fixtures/ingredients.json.zip...
-> fixture size: 5.03 MB
-> saving to temp file /tmp/tmph_fl0esl.json.zip
Installed 78854 object(s) from 1 fixture(s)
-> removing temp file

Downloading fixture data from https://github.com/wger-project/data/raw/master/fixtures/weight_units.json.zip...
-> fixture size: 0.0201 MB
-> saving to temp file /tmp/tmpc7zfenk3.json.zip
Installed 1897 object(s) from 1 fixture(s)
-> removing temp file

Downloading fixture data from https://github.com/wger-project/data/raw/master/fixtures/ingredient_units.json.zip...
-> fixture size: 0.13 MB
-> saving to temp file /tmp/tmp1nwmvv97.json.zip
Installed 14274 object(s) from 1 fixture(s)
-> removing temp file
```

Best regards

**Comment by rolandgeider** [comment]
Good catch! I guess this slipped through the cracks when we did the big exercise model refactoring

**Comment by rolandgeider** [comment]
Fixed with https://github.com/wger-project/wger/commit/787337550bbf3d9b77edc4a04a84f264fd79618e
