### ISSUE TITLE
Error whe adding an image to an exercise

### ISSUE THREAD

**Issue by ameisehaufen** [wger-project/docker#6]
When I try to add an image to an exercise I got the error Key (id)=(4) already exists. If I keep trying the number will be increasing and sometimes it will eventually work. It happen after a fresh install from version 2.0-dev using docker-compose (as described in https://github.com/wger-project/docker). If I try to do it on another exercise the problem is the same and the key (id) keeps increasing by one at time. Can I change key ID by an Unix timestamp?

## The error log is:

```
(Request Method: | POST
-- | --
http://10.0.0.10/pt/exercise/image/160/image/add
3.1.7
IntegrityError
duplicate key value violates unique constraint "exercises_exerciseimage_pkey" DETAIL:  Key (id)=(4) already exists.
/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py, line 84, in _execute
/usr/bin/python3
3.8.5
['/usr/local/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/dist-packages',  '/home/wger/src',  '/usr/lib/python3/dist-packages']
Thu, 25 Mar 2021 16:32:54 +0100)
```

### Environment:

```
Request Method: POST
Request URL: http://10.0.0.10/pt/exercise/image/160/image/add

Django Version: 3.1.7
Python Version: 3.8.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_extensions',
 'storages',
 'wger.config',
 'wger.core',
 'wger.mailer',
 'wger.exercises',
 'wger.gym',
 'wger.manager',
 'wger.nutrition',
 'wger.software',
 'wger.utils',
 'wger.weight',
 'captcha',
 'django.contrib.sitemaps',
 'easy_thumbnails',
 'compressor',
 'crispy_forms',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_bootstrap_breadcrumbs',
 'corsheaders')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'wger.utils.middleware.JavascriptAJAXRedirectionMiddleware',
 'wger.utils.middleware.WgerAuthenticationMiddleware',
 'wger.utils.middleware.RobotsExclusionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware')



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (duplicate key value violates unique constraint "exercises_exerciseimage_pkey"
DETAIL:  Key (id)=(4) already exists.
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wger/src/wger/utils/generic_views.py", line 199, in dispatch
    return super(WgerFormMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/wger/src/wger/exercises/views/images.py", line 99, in form_valid
    return super(ExerciseImageAddView, self).form_valid(form)
  File "/home/wger/src/wger/utils/generic_views.py", line 246, in form_valid
    return super(WgerFormMixin, self).form_valid(form)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/usr/local/lib/python3.8/dist-packages/django/forms/models.py", line 460, in save
    self.instance.save()
  File "/home/wger/src/wger/exercises/models.py", line 502, in save
    super(ExerciseImage, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /pt/exercise/image/160/image/add
Exception Value: duplicate key value violates unique constraint "exercises_exerciseimage_pkey"
DETAIL:  Key (id)=(4) already exists.
```

**Comment by rolandgeider** [comment]
That's interesting (and obviously a bug). It's also interesting that it clashes with an id when it should add a new one. Does the docker imagine have already exercise images?

**Comment by ameisehaufen** [comment]
The docker image hasn't images, but, after using docker compose, I generate the images using the command

`docker-compose exec web python3 manage.py download-exercise-images`

`docker-compose exec web wger load-online-fixtures`

Without any error message.

I even tried to exec `docker-compose exec web python3 manage.py migrate`, but it didn't solved the issue.

I used the docker-compose up -d, in a fresh install, using the following docker-compose.yml and prod.env below.
I just changed the port (from 80 to 58148), and volumes, but I think the problem is not related to that.

## docker-compose.yml
```yml
version: '3.7'

services:
  web:
    image: wger/devel:latest
    volumes:
      - /home/camargo/AppSys/wger/static:/home/wger/static
      - /home/camargo/AppSys/wger/media:/home/wger/media
    ports:
      - 8000
    env_file:
      - ./prod.env
    depends_on:
      - db
      - cache

  nginx:
    build: ./nginx
    volumes:
      - /home/camargo/AppSys/wger/static:/wger/static:ro
      - /home/camargo/AppSys/wger/media:/wger/media:ro
    ports:
      - 58148:80
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine
    volumes:
      - /home/camargo/AppSys/wger/postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger

  cache:
    restart: always
    image: redis:latest
    expose:
      - 6379

volumes:
  postgres-data:
  static:
  media:
```
## prod.env

```sh
# Database
DJANGO_DB_ENGINE=django.db.backends.postgresql
DJANGO_DB_DATABASE=wger
DJANGO_DB_USER=wger
DJANGO_DB_PASSWORD=wger
DJANGO_DB_HOST=db
DJANGO_DB_PORT=5432

# Cache
DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache
DJANGO_CACHE_LOCATION=redis://cache:6379/1
DJANGO_CACHE_TIMEOUT= 1296000
# 60*60*24*15, 15 Days
DJANGO_CACHE_CLIENT_CLASS=django_redis.client.DefaultClient

DJANGO_MEDIA_ROOT=/home/wger/media

# Change the secret key to a random string if you are running this instance publicly
SECRET_KEY=mysecretkey


# Application
ALLOW_REGISTRATION=True
ALLOW_GUEST_USERS=False

# Others
DJANGO_DEBUG=False
WGER_USE_GUNICORN=True
TIME_ZONE=Europe/Berlin
SITE_URL=http://localhost:8000
```

**Comment by rolandgeider** [comment]
Found the error, the exercise images were being identified by their ID, so if there were locally uploaded images they would clash when (or after) running download-exercise-images. I'll add a UUID as we do with the exercises so it's possible to properly reference them

**Comment by rolandgeider** [comment]
I've commited a fix in master, but want to test whether the autoincrement ID needs to be reset on the database since it was being set manually in the download script (also, running the script will not work till the website is updated)

**Comment by ameisehaufen** [comment]
Ok, I will wait for the tests. Thank you! Really nice software.

**Comment by rolandgeider** [comment]
you _might_ have to change the postgres sequence for the image IDs. For that, you will need to exec into the DB container and do something like this:

```sql
ALTER SEQUENCE exercises_exerciseimage_id_seq RESTART WITH 500;
```

I'm also not sure whether you need to to reload the exercise and exercise base fixtures, probably not. So, depending on how much data you have entered, it might be faster to drop the DB and pull a new version 
(while I was looking into this, I refactored the image script, it should be way faster now)

**Comment by ameisehaufen** [comment]
Thanks! I was just starting to add pictures, so I will drop the DP and pull the new version.

**Comment by rolandgeider** [comment]
Great! Closing here, if you encounter the problem again, just re-open
